apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ai-chatbot-web-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 12000
      targetPort: 80
      nodePort: 32000
      protocol: TCP
