apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ai-chatbot-web-service
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 12000
      protocol: TCP
